# Generated by Django 3.1.3 on 2020-11-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('typeofcertificate', models.CharField(choices=[('D', 'Death Certificate'), ('B', 'Birth Certificate'), ('R', 'Revenue Certificate'), ('C', 'Contract Certificate')], default='B', max_length=1)),
                ('empid', models.CharField(default=0, max_length=100)),
                ('fileid', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('N', 'No Action'), ('A', 'Action'), ('V', 'Verified')], default='N', max_length=1)),
            ],
        ),
    ]
