# Generated by Django 3.1 on 2020-08-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='empid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
