# Generated by Django 3.1 on 2020-08-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='helo', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(default='12345', max_length=32),
        ),
    ]
