# Generated by Django 3.1 on 2020-08-21 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(default='NULL', max_length=50, verbose_name='Name of Applicant')),
                ('application_no', models.CharField(default='NULL', max_length=50, verbose_name='Application Number')),
                ('phone_no', models.CharField(default='NULL', max_length=15, verbose_name='Phone')),
                ('recent_application', models.CharField(choices=[('Birth Certificate', 'Birth Certificate'), ('Death Certificate', 'Death Certificate'), ('Marriage Certificate', 'Marriage Certificate'), ('License', 'License')], default='NULL', max_length=500, verbose_name='Recent Application')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
