# Generated by Django 3.1.3 on 2020-11-07 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(default='NULL', max_length=50, null='false', verbose_name='Q1')),
                ('two', models.CharField(default='NULL', max_length=50, null='false', verbose_name='Q2')),
                ('three', models.CharField(default='NULL', max_length=50, null='false', verbose_name='Q3')),
                ('four', models.CharField(default='NULL', max_length=50, null='false', verbose_name='Q4')),
                ('five', models.CharField(default='NULL', max_length=50, null='false', verbose_name='Q5')),
                ('six', models.CharField(default='NULL', max_length=50, null='false', verbose_name='Q6')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(default='NULL', max_length=50, null='true', verbose_name='Name of Applicant')),
                ('application_no', models.CharField(default='NULL', max_length=50, null='true', verbose_name='Application Number')),
                ('phone_no', models.CharField(default='NULL', max_length=15, null='true', verbose_name='Phone')),
                ('recent_application', models.CharField(choices=[('Birth Certificate', 'Birth Certificate'), ('Death Certificate', 'Death Certificate'), ('Marriage Certificate', 'Marriage Certificate'), ('License', 'License')], default='NULL', max_length=50, null='true', verbose_name='Recent Application ')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
