# Generated by Django 3.1 on 2020-08-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(default='NULL', max_length=50, verbose_name='Q1')),
                ('two', models.CharField(default='NULL', max_length=50, verbose_name='Q2')),
                ('three', models.CharField(default='NULL', max_length=50, verbose_name='Q3')),
                ('four', models.CharField(default='NULL', max_length=50, verbose_name='Q4')),
                ('five', models.CharField(default='NULL', max_length=50, verbose_name='Q5')),
                ('six', models.CharField(default='NULL', max_length=50, verbose_name='Q6')),
            ],
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='recent_application',
            field=models.CharField(choices=[('Birth Certificate', 'Birth Certificate'), ('Death Certificate', 'Death Certificate'), ('Marriage Certificate', 'Marriage Certificate'), ('License', 'License')], default='NULL', max_length=50, verbose_name='Recent Application '),
        ),
    ]
