# Generated by Django 3.1 on 2020-08-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_auto_20200822_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_details',
            name='applicant_name',
            field=models.CharField(default='NULL', max_length=50, null='true', verbose_name='Name of Applicant'),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='application_no',
            field=models.CharField(default='NULL', max_length=50, null='true', verbose_name='Application Number'),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='phone_no',
            field=models.CharField(default='NULL', max_length=15, null='true', verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='recent_application',
            field=models.CharField(choices=[('Birth Certificate', 'Birth Certificate'), ('Death Certificate', 'Death Certificate'), ('Marriage Certificate', 'Marriage Certificate'), ('License', 'License')], default='NULL', max_length=50, null='true', verbose_name='Recent Application '),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='five',
            field=models.CharField(default='NULL', max_length=50, null='true', verbose_name='Q5'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='four',
            field=models.CharField(default='NULL', max_length=50, null='true', verbose_name='Q4'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='one',
            field=models.CharField(default='NULL', max_length=50, null='true', verbose_name='Q1'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='six',
            field=models.CharField(default='NULL', max_length=50, null='true', verbose_name='Q6'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='three',
            field=models.CharField(default='NULL', max_length=50, null='true', verbose_name='Q3'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='two',
            field=models.CharField(default='NULL', max_length=50, null='true', verbose_name='Q2'),
        ),
    ]
